[package]
name = "rust-paint"
version = "0.1.0"
edition = "2021"
authors = ["danc", "jori", "anas", "raph", "raul"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
nannou_egui = "*"
nannou_audio = "*"
